name:   Create Milestones
on:
    push:
        tags:
          - 'v*.*.*'
env:
  GH_TOKEN: ${{ secrets.GIT_TOKEN }}
  GITHUB_TOKEN: ${{ github.token }}
permissions:
  contents: write
  id-token: write
  pull-requests: write
jobs:
  create-new-release:
    name: Create Milestones 🎉
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
           
    